---
- name: Configure VM for running Bwb workflows
  hosts: all

  roles:
    - {role: docker, become: yes, docker_install_compose: no}
    - bwb-setup

  tasks:
  - name: Execute distribution upgrade
    become: yes
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
      upgrade: dist
      autoremove: yes
      autoclean: yes

  - name: Check if reboot required
    ansible.builtin.stat:
      path: /var/run/reboot-required
    register: reboot_required

  - name: Reboot if required
    become: yes
    ansible.builtin.reboot:
      reboot_timeout: 300
    when: reboot_required.stat.exists == true
